language: node_js

node_js:
  - stable

branches:
  only:
    - master

install:
  - npm install

script:
  - npm tests

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
